### ISSUE TITLE
eager beavers

### ISSUE THREAD

**Issue by cronecode** [cronecode/nest-witch#14]
There's an edge case where a player clicks 'refine' after having played every episode. Maybe they should get an alert saying something to the effect of 'come back later'? Can't think of a solution that doesn't break immersion.

**Comment by LiamAttClarke** [comment]
What about a message to the effect of: "Your power level is over 9000! The system cannot process your greatness at this time."

**Comment by cronecode** [comment]
closing as one of many bathwatered babies
