### ISSUE TITLE
matchmaker.js is incomplete

### ISSUE THREAD

**Issue by cronecode** [cronecode/nest-witch#2]
I'm hung up on the last step of the matchmaker sequence. If the filterEpisodes function returns more than one episode, the index should be incremented and the function should be called again on the new array.

That being said, I have a pretty good feeling that the whole thing is unnecessarily complicated, so maybe there's a better approach.

**Comment by LiamAttClarke** [comment]
I think we can improve on this approach. I have a method in mind that uses a weighted random number generator where the weights are determined by a score that is calculated for each episode. With this approach we wouldn't need to sort the episodes. The score for each episode would be the sum of property values on the player (blue, green, circle, square) multiplied by a 0 or 1 based on the presence of the property on a given episode. To be continued...

**Comment by LiamAttClarke** [comment]
PR: https://github.com/cronecode/nest-witch/pull/3

**Comment by cronecode** [comment]
Merged!

**Comment by LiamAttClarke** [comment]
Aww yiss!
