### ISSUE TITLE
'quality' data attr in template

### ISSUE THREAD

**Issue by cronecode** [cronecode/nest-witch#4]
This is currently being passed to the click handler as a string, but passing an object ({quality: String, value: Number || Boolean}) would be way more useful. Is that possible?

**Comment by LiamAttClarke** [comment]
I believe so. Assuming you set the data-quality attribute with a valid json string (ie data-quality="{"quality": 10}"), it should convert to a js object when read.

**Comment by LiamAttClarke** [comment]
It is!
PR: https://github.com/cronecode/nest-witch/pull/5

**Comment by cronecode** [comment]
Merged!
