### ISSUE TITLE
TODO: landing page

### ISSUE THREAD

**Issue by cronecode** [cronecode/nest-witch#7]
The landing page will be what the game displays on load if it doesn't find a current game or if the user resets the current game. It will play a brief intro with cheesily animated text and then load the first episode.

**Comment by LiamAttClarke** [comment]
I'll have to break into my cache of Cheez Whiz for this one.

**Comment by cronecode** [comment]
All the web dev tutorials I've read clearly indicate that the Cheez Whiz should always be close at hand.

**Comment by cronecode** [comment]
No Cheez yet, but the landing page is up & functional (see index.pug).
