### ISSUE TITLE
TODO: game state persistence

### ISSUE THREAD

**Issue by cronecode** [cronecode/nest-witch#8]
On load, the game should display:

a) the landing page, if player.pattern and player.played are empty
b) the home page, if the player has completed at least one episode but hasn't started a new one
c) the current scene, if the player is in-episode

**Comment by LiamAttClarke** [comment]
Have you decided on how you want to persist users? Cookies/ Database? My recommendation is to use cookies. With cookies you can persist the data without having to deal with authentication and cookies have the added functionality in that they are sent with every request to the server.

**Comment by cronecode** [comment]
I'm actually wondering if localStorage might be the way to go for the version of the game that'll be at the showcase. Am I right in thinking that it would be pretty simple to swap out for server-side persistence later?

**Comment by LiamAttClarke** [comment]
Yes, LocalStorage is a great option since it doesn't expire like cookies! Server-side persistence will probably not be as simple. Generally you will have to deal with user authentication. One option (which I recommend) is to have users authenticate using their Google/Facebook accounts.

**Comment by cronecode** [comment]
localStorage has been implemented.
